package com.example.roomwordsample.Databases

import android.content.Context
import androidx.room.Database
import androidx.room.Room
import androidx.room.RoomDatabase
import androidx.sqlite.db.SupportSQLiteDatabase
import com.example.roomwordsample.DAO.WordDao
import com.example.roomwordsample.Entities.Word
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch

@Database(entities = [Word::class], version = 1)
abstract class WordRoomDatabase: RoomDatabase() {

    abstract fun wordDao(): WordDao

    companion object {
        @Volatile
        private var INSTANCE: WordRoomDatabase? = null

        fun getDatabase(
            context: Context,
            scope: CoroutineScope
        ): WordRoomDatabase {
            return INSTANCE ?: synchronized(this) {
                // Create database here
                val instance = Room.databaseBuilder(
                    context.applicationContext,
                    WordRoomDatabase::class.java,
                    "Word_database"
                ).addCallback(WordDatabaseCallback(scope))
                    .build()
                    INSTANCE = instance
                instance
            }
        }
    }

    private class WordDatabaseCallback(
        private val scope: CoroutineScope
    ) : RoomDatabase.Callback() {

        override fun onOpen(db: SupportSQLiteDatabase) {
            super.onOpen(db)
            INSTANCE?.let { database ->
                scope.launch(Dispatchers.IO) {
                    populateDatabase(database.wordDao())
                }
            }
        }

        suspend fun populateDatabase(wordDao: WordDao) {
            wordDao.deleteAll()

            var word: Word
            word = Word(0,"Palabra001")
            wordDao.insert(word)
            word = Word(0,"Palabra002")
            wordDao.insert(word)
            word = Word(0,"Palabra003")
            wordDao.insert(word)
            word = Word(0,"Palabra004")
            wordDao.insert(word)
            word = Word(0,"Palabra005")
            wordDao.insert(word)
            word = Word(0,"Palabra006")
            wordDao.insert(word)
            word = Word(0,"Palabra007")
            wordDao.insert(word)
            word = Word(0,"Palabra008")
            wordDao.insert(word)
            word = Word(0,"Palabra009")
            wordDao.insert(word)
            word = Word(0,"Palabra010")
            wordDao.insert(word)
            word = Word(0,"Palabra011")
            wordDao.insert(word)
            word = Word(0,"Palabra012")
            wordDao.insert(word)
            word = Word(0,"Palabra013")
            wordDao.insert(word)
            word = Word(0,"Palabra014")
            wordDao.insert(word)
            word = Word(0,"Palabra015")
            wordDao.insert(word)
            word = Word(0,"Palabra016")
            wordDao.insert(word)
            word = Word(0,"Palabra017")
            wordDao.insert(word)
            word = Word(0,"Palabra018")
            wordDao.insert(word)
            word = Word(0,"Palabra019")
            wordDao.insert(word)
            word = Word(0,"Palabra020")
            wordDao.insert(word)
            /*word = Word("Palabra021")
            wordDao.insert(word)
            word = Word("Palabra022")
            wordDao.insert(word)
            word = Word("Palabra023")
            wordDao.insert(word)
            word = Word("Palabra024")
            wordDao.insert(word)
            word = Word("Palabra025")
            wordDao.insert(word)
            word = Word("Palabra026")
            wordDao.insert(word)
            word = Word("Palabra027")
            wordDao.insert(word)
            word = Word("Palabra028")
            wordDao.insert(word)
            word = Word("Palabra029")
            wordDao.insert(word)
            word = Word("Palabra030")
            wordDao.insert(word)
            word = Word("Palabra031")
            wordDao.insert(word)
            word = Word("Palabra032")
            wordDao.insert(word)
            word = Word("Palabra033")
            wordDao.insert(word)
            word = Word("Palabra034")
            wordDao.insert(word)
            word = Word("Palabra035")
            wordDao.insert(word)
            word = Word("Palabra036")
            wordDao.insert(word)
            word = Word("Palabra037")
            wordDao.insert(word)
            word = Word("Palabra038")
            wordDao.insert(word)
            word = Word("Palabra039")
            wordDao.insert(word)
            word = Word("Palabra040")
            wordDao.insert(word)
            word = Word("Palabra041")
            wordDao.insert(word)
            word = Word("Palabra042")
            wordDao.insert(word)
            word = Word("Palabra043")
            wordDao.insert(word)
            word = Word("Palabra044")
            wordDao.insert(word)
            word = Word("Palabra045")
            wordDao.insert(word)
            word = Word("Palabra046")
            wordDao.insert(word)
            word = Word("Palabra047")
            wordDao.insert(word)
            word = Word("Palabra048")
            wordDao.insert(word)
            word = Word("Palabra049")
            wordDao.insert(word)
            word = Word("Palabra050")
            wordDao.insert(word)
            word = Word("Palabra051")
            wordDao.insert(word)
            word = Word("Palabra052")
            wordDao.insert(word)
            word = Word("Palabra053")
            wordDao.insert(word)
            word = Word("Palabra054")
            wordDao.insert(word)
            word = Word("Palabra055")
            wordDao.insert(word)
            word = Word("Palabra056")
            wordDao.insert(word)
            word = Word("Palabra057")
            wordDao.insert(word)
            word = Word("Palabra058")
            wordDao.insert(word)
            word = Word("Palabra059")
            wordDao.insert(word)
            word = Word("Palabra060")
            wordDao.insert(word)
            word = Word("Palabra061")
            wordDao.insert(word)
            word = Word("Palabra062")
            wordDao.insert(word)
            word = Word("Palabra063")
            wordDao.insert(word)
            word = Word("Palabra064")
            wordDao.insert(word)
            word = Word("Palabra065")
            wordDao.insert(word)
            word = Word("Palabra066")
            wordDao.insert(word)
            word = Word("Palabra067")
            wordDao.insert(word)
            word = Word("Palabra068")
            wordDao.insert(word)
            word = Word("Palabra069")
            wordDao.insert(word)
            word = Word("Palabra070")
            wordDao.insert(word)
            word = Word("Palabra071")
            wordDao.insert(word)
            word = Word("Palabra072")
            wordDao.insert(word)
            word = Word("Palabra073")
            wordDao.insert(word)
            word = Word("Palabra074")
            wordDao.insert(word)
            word = Word("Palabra075")
            wordDao.insert(word)
            word = Word("Palabra076")
            wordDao.insert(word)
            word = Word("Palabra077")
            wordDao.insert(word)
            word = Word("Palabra078")
            wordDao.insert(word)
            word = Word("Palabra079")
            wordDao.insert(word)
            word = Word("Palabra080")
            wordDao.insert(word)
            word = Word("Palabra081")
            wordDao.insert(word)
            word = Word("Palabra082")
            wordDao.insert(word)
            word = Word("Palabra083")
            wordDao.insert(word)
            word = Word("Palabra084")
            wordDao.insert(word)
            word = Word("Palabra085")
            wordDao.insert(word)
            word = Word("Palabra086")
            wordDao.insert(word)
            word = Word("Palabra087")
            wordDao.insert(word)
            word = Word("Palabra088")
            wordDao.insert(word)
            word = Word("Palabra089")
            wordDao.insert(word)
            word = Word("Palabra090")
            wordDao.insert(word)
            word = Word("Palabra091")
            wordDao.insert(word)
            word = Word("Palabra092")
            wordDao.insert(word)
            word = Word("Palabra093")
            wordDao.insert(word)
            word = Word("Palabra094")
            wordDao.insert(word)
            word = Word("Palabra095")
            wordDao.insert(word)
            word = Word("Palabra096")
            wordDao.insert(word)
            word = Word("Palabra097")
            wordDao.insert(word)
            word = Word("Palabra098")
            wordDao.insert(word)
            word = Word("Palabra099")
            wordDao.insert(word)
            word = Word("Palabra100")
            wordDao.insert(word)
            word = Word("Palabra101")
            wordDao.insert(word)
            word = Word("Palabra102")
            wordDao.insert(word)
            word = Word("Palabra103")
            wordDao.insert(word)
            word = Word("Palabra104")
            wordDao.insert(word)
            word = Word("Palabra105")
            wordDao.insert(word)
            word = Word("Palabra106")
            wordDao.insert(word)
            word = Word("Palabra107")
            wordDao.insert(word)
            word = Word("Palabra108")
            wordDao.insert(word)
            word = Word("Palabra109")
            wordDao.insert(word)
            word = Word("Palabra110")
            wordDao.insert(word)
            word = Word("Palabra111")
            wordDao.insert(word)
            word = Word("Palabra112")
            wordDao.insert(word)
            word = Word("Palabra113")
            wordDao.insert(word)
            word = Word("Palabra114")
            wordDao.insert(word)
            word = Word("Palabra115")
            wordDao.insert(word)
            word = Word("Palabra116")
            wordDao.insert(word)
            word = Word("Palabra117")
            wordDao.insert(word)
            word = Word("Palabra118")
            wordDao.insert(word)
            word = Word("Palabra119")
            wordDao.insert(word)
            word = Word("Palabra120")
            wordDao.insert(word)
            word = Word("Palabra121")
            wordDao.insert(word)
            word = Word("Palabra122")
            wordDao.insert(word)
            word = Word("Palabra123")
            wordDao.insert(word)
            word = Word("Palabra124")
            wordDao.insert(word)
            word = Word("Palabra125")
            wordDao.insert(word)
            word = Word("Palabra126")
            wordDao.insert(word)
            word = Word("Palabra127")
            wordDao.insert(word)
            word = Word("Palabra128")
            wordDao.insert(word)
            word = Word("Palabra129")
            wordDao.insert(word)
            word = Word("Palabra130")
            wordDao.insert(word)
            word = Word("Palabra131")
            wordDao.insert(word)
            word = Word("Palabra132")
            wordDao.insert(word)
            word = Word("Palabra133")
            wordDao.insert(word)
            word = Word("Palabra134")
            wordDao.insert(word)
            word = Word("Palabra135")
            wordDao.insert(word)
            word = Word("Palabra136")
            wordDao.insert(word)
            word = Word("Palabra137")
            wordDao.insert(word)
            word = Word("Palabra138")
            wordDao.insert(word)
            word = Word("Palabra139")
            wordDao.insert(word)
            word = Word("Palabra140")
            wordDao.insert(word)
            word = Word("Palabra141")
            wordDao.insert(word)
            word = Word("Palabra142")
            wordDao.insert(word)
            word = Word("Palabra143")
            wordDao.insert(word)
            word = Word("Palabra144")
            wordDao.insert(word)
            word = Word("Palabra145")
            wordDao.insert(word)
            word = Word("Palabra146")
            wordDao.insert(word)
            word = Word("Palabra147")
            wordDao.insert(word)
            word = Word("Palabra148")
            wordDao.insert(word)
            word = Word("Palabra149")
            wordDao.insert(word)
            word = Word("Palabra150")
            wordDao.insert(word)
            word = Word("Palabra151")
            wordDao.insert(word)
            word = Word("Palabra152")
            wordDao.insert(word)
            word = Word("Palabra153")
            wordDao.insert(word)
            word = Word("Palabra154")
            wordDao.insert(word)
            word = Word("Palabra155")
            wordDao.insert(word)
            word = Word("Palabra156")
            wordDao.insert(word)
            word = Word("Palabra157")
            wordDao.insert(word)
            word = Word("Palabra158")
            wordDao.insert(word)
            word = Word("Palabra159")
            wordDao.insert(word)
            word = Word("Palabra160")
            wordDao.insert(word)
            word = Word("Palabra161")
            wordDao.insert(word)
            word = Word("Palabra162")
            wordDao.insert(word)
            word = Word("Palabra163")
            wordDao.insert(word)
            word = Word("Palabra164")
            wordDao.insert(word)
            word = Word("Palabra165")
            wordDao.insert(word)
            word = Word("Palabra166")
            wordDao.insert(word)
            word = Word("Palabra167")
            wordDao.insert(word)
            word = Word("Palabra168")
            wordDao.insert(word)
            word = Word("Palabra169")
            wordDao.insert(word)
            word = Word("Palabra170")
            wordDao.insert(word)
            word = Word("Palabra171")
            wordDao.insert(word)
            word = Word("Palabra172")
            wordDao.insert(word)
            word = Word("Palabra173")
            wordDao.insert(word)
            word = Word("Palabra174")
            wordDao.insert(word)
            word = Word("Palabra175")
            wordDao.insert(word)
            word = Word("Palabra176")
            wordDao.insert(word)
            word = Word("Palabra177")
            wordDao.insert(word)
            word = Word("Palabra178")
            wordDao.insert(word)
            word = Word("Palabra179")
            wordDao.insert(word)
            word = Word("Palabra180")
            wordDao.insert(word)
            word = Word("Palabra181")
            wordDao.insert(word)
            word = Word("Palabra182")
            wordDao.insert(word)
            word = Word("Palabra183")
            wordDao.insert(word)
            word = Word("Palabra184")
            wordDao.insert(word)
            word = Word("Palabra185")
            wordDao.insert(word)
            word = Word("Palabra186")
            wordDao.insert(word)
            word = Word("Palabra187")
            wordDao.insert(word)
            word = Word("Palabra188")
            wordDao.insert(word)
            word = Word("Palabra189")
            wordDao.insert(word)
            word = Word("Palabra190")
            wordDao.insert(word)
            word = Word("Palabra191")
            wordDao.insert(word)
            word = Word("Palabra192")
            wordDao.insert(word)
            word = Word("Palabra193")
            wordDao.insert(word)
            word = Word("Palabra194")
            wordDao.insert(word)
            word = Word("Palabra195")
            wordDao.insert(word)
            word = Word("Palabra196")
            wordDao.insert(word)
            word = Word("Palabra197")
            wordDao.insert(word)
            word = Word("Palabra198")
            wordDao.insert(word)
            word = Word("Palabra199")
            wordDao.insert(word)
            word = Word("Palabra200")
            wordDao.insert(word)*/

        }
    }

}